import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import StoreProvider from "../store/StoreProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { PostHogProvider } from "@/shared/PostHogProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <PostHogProvider>
          <StoreProvider>
            <Navbar />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </StoreProvider>
        </PostHogProvider>
      </body>
    </html>
  );
}
